name: stims
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1
  - pydantic=2.10.1
  - pydantic-core=2.27.1
  - python=3.13.3
  - python_abi=3.13
  - readline=8.2
  - tk=8.6.13
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b